"""Add account stages tracking

Revision ID: b1908fa01c8f
Revises: 
Create Date: 2025-06-03 15:54:33.986823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1908fa01c8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_name', sa.String(length=200), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=False),
    sa.Column('website_domain', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('script_type', sa.String(length=50), nullable=True),
    sa.Column('script_content', sa.Text(), nullable=False),
    sa.Column('form_selectors', sa.JSON(), nullable=True),
    sa.Column('required_fields', sa.JSON(), nullable=True),
    sa.Column('optional_fields', sa.JSON(), nullable=True),
    sa.Column('captcha_present', sa.Boolean(), nullable=True),
    sa.Column('email_verification_required', sa.Boolean(), nullable=True),
    sa.Column('wait_times', sa.JSON(), nullable=True),
    sa.Column('retry_settings', sa.JSON(), nullable=True),
    sa.Column('browser_settings', sa.JSON(), nullable=True),
    sa.Column('learning_data', sa.JSON(), nullable=True),
    sa.Column('common_errors', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('successful_runs', sa.Integer(), nullable=True),
    sa.Column('failed_runs', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_run', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signup_scripts_id'), 'signup_scripts', ['id'], unique=False)
    op.create_index(op.f('ix_signup_scripts_website_domain'), 'signup_scripts', ['website_domain'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('master_key_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('encrypted_first_name', sa.Text(), nullable=True),
    sa.Column('encrypted_last_name', sa.Text(), nullable=True),
    sa.Column('encrypted_email', sa.Text(), nullable=True),
    sa.Column('encrypted_phone', sa.Text(), nullable=True),
    sa.Column('encrypted_date_of_birth', sa.Text(), nullable=True),
    sa.Column('encrypted_address_line1', sa.Text(), nullable=True),
    sa.Column('encrypted_address_line2', sa.Text(), nullable=True),
    sa.Column('encrypted_city', sa.Text(), nullable=True),
    sa.Column('encrypted_state', sa.Text(), nullable=True),
    sa.Column('encrypted_zip_code', sa.Text(), nullable=True),
    sa.Column('encrypted_country', sa.Text(), nullable=True),
    sa.Column('encrypted_profession', sa.Text(), nullable=True),
    sa.Column('encrypted_company', sa.Text(), nullable=True),
    sa.Column('encrypted_bio', sa.Text(), nullable=True),
    sa.Column('encrypted_custom_fields', sa.Text(), nullable=True),
    sa.Column('preferred_username_pattern', sa.String(length=100), nullable=True),
    sa.Column('password_preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identities_id'), 'identities', ['id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('website_name', sa.String(length=200), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=False),
    sa.Column('website_domain', sa.String(length=200), nullable=True),
    sa.Column('encrypted_username', sa.Text(), nullable=True),
    sa.Column('encrypted_email', sa.Text(), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('signup_completed', sa.Boolean(), nullable=True),
    sa.Column('account_type', sa.String(length=100), nullable=True),
    sa.Column('signup_method', sa.String(length=50), nullable=True),
    sa.Column('encrypted_security_questions', sa.Text(), nullable=True),
    sa.Column('encrypted_notes', sa.Text(), nullable=True),
    sa.Column('signup_script_id', sa.Integer(), nullable=True),
    sa.Column('signup_attempts', sa.Integer(), nullable=True),
    sa.Column('last_signup_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['signup_script_id'], ['signup_scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_website_domain'), 'accounts', ['website_domain'], unique=False)
    op.create_table('account_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('stage_type', sa.Enum('EMAIL_VERIFICATION', 'PHONE_VERIFICATION', 'PROFILE_SETUP', 'TWO_FACTOR_AUTH', 'DOCUMENT_VERIFICATION', 'CAPTCHA', 'HUMAN_VERIFICATION', 'TERMS_ACCEPTANCE', 'EMAIL_CONFIRMATION', 'ACCOUNT_ACTIVATION', name='stagetype'), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=False),
    sa.Column('stage_description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'SKIPPED', 'NOT_REQUIRED', name='stagestatus'), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('encrypted_stage_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_stages_id'), 'account_stages', ['id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.String(length=200), nullable=False),
    sa.Column('key_type', sa.String(length=100), nullable=False),
    sa.Column('encrypted_key_value', sa.Text(), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_rotate', sa.Boolean(), nullable=True),
    sa.Column('rotation_interval_days', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=500), nullable=True),
    sa.Column('encrypted_additional_data', sa.Text(), nullable=True),
    sa.Column('encrypted_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_account_stages_id'), table_name='account_stages')
    op.drop_table('account_stages')
    op.drop_index(op.f('ix_accounts_website_domain'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_identities_id'), table_name='identities')
    op.drop_table('identities')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_signup_scripts_website_domain'), table_name='signup_scripts')
    op.drop_index(op.f('ix_signup_scripts_id'), table_name='signup_scripts')
    op.drop_table('signup_scripts')
    # ### end Alembic commands ### 