#!/usr/bin/env python3
"""fuze-code-review verdict gate — the ONE decision that may fire `gh pr review --approve`.

WHY THIS EXISTS. `fuze-code-review.yml` asks an LLM (via fuze-code-action) to review a PR
diff and, when the review is genuinely clean, submit an APPROVING review so a bot-authored
PR can satisfy `required_approving_review_count: 1` + `require_last_push_approval: true`
without a human. An approval step that fires unconditionally is WORSE than no review gate at
all, because it LOOKS like a gate and is not — this fleet has spent weeks removing exactly
that shape (`|| true`, `continue-on-error`, a check that passes by not running). This script
is the single place that decides approve / request_changes / comment / abstain, so the
workflow itself never has to parse LLM output inline.

THE CONTRACT. The reviewer LLM is instructed to emit, after its prose, a JSON object between
two sentinel lines carrying a per-run NONCE:

    ===FUZE_REVIEW_VERDICT_JSON:<nonce>===
    {"verdict": "approve|request_changes|comment", "summary": "...", "findings": [...]}
    ===END_FUZE_REVIEW_VERDICT_JSON:<nonce>===

The nonce is generated by the WORKFLOW at run time, after the PR diff is already fixed, and
is never predictable from the diff content — so a PR whose diff contains a forged sentinel
block (prompt injection via a file that quotes this exact contract) cannot forge a match
without also guessing 128 bits of randomness drawn after that diff was written. The LAST
occurrence of the nonce-scoped block is used, which is a second, independent line of defense:
even a lucky nonce match earlier in the transcript (e.g. the model quoting the instructions
back) is expected to be superseded by the model's actual answer at the end.

FAIL-CLOSED RULES, encoded as data rather than left to the workflow's YAML `if:` conditions,
so they can be unit-tested directly and mutation-tested (flip any one of them and a test
must fail):

  1. fuze-code-action's own `conclusion` must be "success". Anything else (the provider
     chain was exhausted, errored, or never started) is an ABSTAIN — "no review was
     produced", never "clean".
  2. The sentinel block must be present exactly once for the given nonce, and must contain
     valid JSON with the exact required shape. Missing, duplicated-with-different-content,
     malformed, or schema-violating is an ABSTAIN. UNPARSEABLE IS NOT CLEAN.
  3. `verdict` must be one of the three known literal values. Anything else is an ABSTAIN.
  4. `verdict == "approve"` is only self-consistent when `findings` is an empty list. A
     model claiming "approve" while also listing findings is a contradiction, not a clean
     review — ABSTAIN (this also defends against a truncated / merged response where two
     answers got concatenated).
  5. A PR touching `.github/workflows/**`, `.github/actions/**`, `workflow-templates/**`,
     `governance/**`, `scripts/apply_ruleset.sh`, or `scripts/bootstrap/**` (the approval
     machinery and the org's governance surface) NEVER gets an automatic approval, no matter
     what the model said — downgraded to "comment" so a human is pulled in. This is a
     structural rule, checked against the actual changed-file list computed by the workflow
     from `git diff`, NOT against anything the model claims about its own diff — a
     self-approving change to the approval machinery must never be able to talk itself past
     this check.

  6. A `mode == "declined"` result on a PR that touches that same sensitive surface is the
     workflow-self-modification guard (claude-code-action refuses to review a PR that changes
     the workflow invoking it) — BY DESIGN, not a failure. It is DEFERRED to a non-approving,
     non-blocking "comment" (the review runs post-merge on the default branch) rather than
     abstained, so a legitimate workflow change is not permanently wedged against a gate that
     structurally cannot run on it. Guarded on BOTH the declined mode AND the sensitive-file
     change, never on `mode` alone: a decline without such a change still fails closed. A
     swallowed provider error does NOT reach this branch as a decline — classify.sh surfaces
     it as an availability failure — so a deferral can never mask a real fault.

  7. THE APPROVE-OR-FAIL CONTRACT (the owner's requirement, rule 7). This check is now MANDATORY:
     "if it ran, the conclusion must be APPROVED or the CI fails and stops." So every
     decision carries a `check` field, "pass" or "fail", and the workflow's decisive step
     exits on it:
       PASS — approve (clean); a model-approve DOWNGRADED by rule 5 (the check keys on the
              MODEL verdict, not on which gh command ran — otherwise every governance PR
              deadlocks); the rule-6 self-mod DEFERRAL; a rule-7 credit-outage; an
              environmental SKIP (main(): no credential / no reviewable diff).
       FAIL — request_changes; a model `comment` verdict on a non-sensitive PR (not an
              approval — this is what triggers the bounded auto-fix loop); a genuine ABSTAIN.

  8. AVAILABILITY / CREDIT OUTAGE (the owner's exception) — "UNLESS the failure is a credit outage."
     A non-success conclusion that fuze-code-action classified as an AVAILABILITY failure
     (its new `availability` output, derived from classify.sh's exit code, NOT from log
     grepping and NOT from `conclusion` alone — a task failure and an exhaustion both report
     conclusion=failure) is an `outage`: a NON-BLOCKING notice, check=PASS, kept DISTINCT
     from a genuine abstain. Because an outage PASSES, the auto-fix loop never fires on it.

Exit code is not the interface; call `decide()` from the workflow's own python step, or run
this file with the documented env vars to have it write GITHUB_OUTPUT directly (see `main`).
"""
from __future__ import annotations

import base64
import binascii
import json
import os
import re
import secrets as _secrets_mod  # nonce generation; unrelated to GitHub Secrets
import sys

VALID_VERDICTS = ("approve", "request_changes", "comment")
# The gh action a decision maps to. `outage` and `skip` are produced by the
# approve-or-fail extension (see decide() / main()); `superseded` by the cancelled-job
# rule at the top of main(); every other value predates them.
DECISIONS = ("approve", "request_changes", "comment", "abstain", "outage", "skip",
             "superseded")

# Whether a decision PASSES or FAILS the (now REQUIRED) fuze-code-review check. This
# is the owner's approve-or-fail contract, encoded as data so the workflow's decisive
# step maps it to an exit code without re-deriving logic, and so it is unit-testable:
#   PASS — the model approved (even when the GitHub review was DOWNGRADED to a
#          comment on a sensitive PR: the check keys on the MODEL verdict, not on
#          which gh command ran, or keying it on the downgrade would deadlock every
#          governance PR); the self-mod guard DEFERRED the review; a credit/quota
#          AVAILABILITY outage (the owner's explicit exception); an environmental
#          SKIP (no credential / no reviewable diff); or a SUPERSEDED run (the review
#          job was cancelled because a newer commit landed).
#   FAIL — request_changes; a model `comment` verdict on a non-sensitive PR (not an
#          approval — this is what triggers the bounded auto-fix loop); or a genuine
#          ABSTAIN (unparseable / self-contradictory output, or a non-success
#          conclusion that is neither an availability outage nor the self-mod
#          deferral). Fail-closed: unparseable is NOT clean.


def make_nonce() -> str:
    """A fresh, unpredictable-in-advance token for one review run's sentinel block."""
    return _secrets_mod.token_hex(16)


def _sentinel_pattern(nonce: str) -> re.Pattern:
    start = re.escape(f"===FUZE_REVIEW_VERDICT_JSON:{nonce}===")
    end = re.escape(f"===END_FUZE_REVIEW_VERDICT_JSON:{nonce}===")
    # DOTALL so the JSON body (which we do not expect to contain newlines, but must not
    # silently mis-parse if a model pretty-prints it) is captured in full. Non-greedy so a
    # transcript containing more than one nonce-scoped block still yields exactly the
    # separate blocks in order, rather than one span from the first start to the last end.
    return re.compile(f"{start}(.*?){end}", re.DOTALL)


def extract_verdict_json(result_text: str, nonce: str) -> tuple[dict | None, str]:
    """Find the LAST nonce-scoped sentinel block in `result_text` and parse it as JSON.

    Returns (parsed_dict_or_None, reason). `reason` is always populated (even on success,
    for logging) and is never assumed to contain secrets — it may itself echo back an
    attacker-controlled snippet, so callers must not treat it as trusted markup, only as a
    log line.
    """
    if not result_text:
        return None, "reviewer produced no output at all"
    if not nonce:
        return None, "internal error: no nonce was supplied to search for"

    matches = _sentinel_pattern(nonce).findall(result_text)
    if not matches:
        return None, "no verdict sentinel block found for this run's nonce"

    # LAST occurrence wins — see module docstring's second line of defense.
    raw = matches[-1].strip()
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError as exc:
        return None, f"verdict block is not valid JSON: {exc}"

    if not isinstance(parsed, dict):
        return None, "verdict block did not decode to a JSON object"

    verdict = parsed.get("verdict")
    if verdict not in VALID_VERDICTS:
        return None, f"verdict field is not one of {VALID_VERDICTS!r}: {verdict!r}"

    findings = parsed.get("findings")
    if not isinstance(findings, list):
        return None, "findings field is missing or not a JSON array"
    for f in findings:
        if not isinstance(f, dict) or "description" not in f:
            return None, "a findings entry is not an object with a description"

    if verdict == "approve" and findings:
        return None, (
            "schema violation: verdict=approve but findings is non-empty — a clean "
            "verdict and reported findings are mutually exclusive"
        )

    summary = parsed.get("summary")
    if not isinstance(summary, str):
        summary = ""

    return {"verdict": verdict, "summary": summary, "findings": findings}, "ok"


def _result(decision, check, reason, *, verdict=None, summary="", findings=None,
            downgraded=False, deferred=False, outage=False) -> dict:
    """A decision dict with EVERY key always present, so callers never have to `.get()`
    a key that one branch happened to omit. `check` is "pass" or "fail" — the single
    thing the workflow's decisive step keys its exit code on."""
    return {
        "decision": decision, "check": check, "reason": reason, "verdict": verdict,
        "summary": summary, "findings": findings or [], "downgraded": downgraded,
        "deferred": deferred, "outage": outage,
    }


def decide(action_conclusion: str, result_text: str, nonce: str,
           sensitive_files: list[str], mode: str = "", availability: bool = False) -> dict:
    """The single decision point. Returns a dict (see `_result`) with keys: decision,
    check ("pass"|"fail" — the approve-or-fail verdict the required check exits on),
    reason, verdict, summary, findings, downgraded (bool: true iff a model "approve" was
    overridden by the sensitive-files rule), deferred (bool: true iff the review was
    legitimately deferred by the workflow-self-modification guard — rule 6), outage
    (bool: true iff a credit/quota AVAILABILITY exhaustion — the owner's exception, rule 7).

    `decision` is always one of DECISIONS. Only `decision == "approve"` may ever result in
    the workflow calling `gh pr review --approve` — every other value must not. `check` is
    the authoritative PASS/FAIL signal; only decisions on the PASS side leave the required
    check green.
    """
    if action_conclusion != "success":
        # RULE 6 — WORKFLOW-SELF-MODIFICATION GUARD IS A DEFERRAL, NOT A FAILURE.
        # claude-code-action deliberately DECLINES to review a PR that modifies the workflow
        # file invoking it (every workflow-migration PR trips it); fuze-code-action reports
        # that as mode == "declined". Nothing ran and nothing is broken — the review runs
        # post-merge on the default branch — so turning the required check red there would
        # permanently wedge every legitimate workflow change against a gate that structurally
        # cannot run on it. Such a decline is DEFERRED (a non-approving, non-blocking
        # "comment", check=PASS) rather than abstained.
        #
        # Guarded on BOTH signals, never on `mode` alone: the decline must coincide with the
        # PR actually touching the sensitive CI/governance surface (the exact precondition for
        # the guard, computed by the workflow from `git diff`). A "declined" with no such
        # change is not the guard but an unexplained no-op, and still fails closed as an
        # abstain. A swallowed provider error no longer reaches here as a decline at all —
        # classify.sh surfaces it as an availability failure — so this branch cannot mask a
        # real auth/quota fault as a benign deferral.
        if mode == "declined" and sensitive_files:
            return _result(
                "comment", "pass",
                "review deferred by claude-code-action's workflow-self-modification "
                "guard: this PR changes CI/governance files (" + ", ".join(sensitive_files)
                + "), which the reviewer refuses to run against on-PR by design. The review "
                "runs post-merge on the default branch. This is NOT a review failure and "
                "does not block the check; the required gates and human review still apply.",
                deferred=True,
            )
        # RULE 7 — AVAILABILITY / CREDIT-OUTAGE EXCEPTION (the owner's explicit "UNLESS the
        # failure is a credit outage"). The provider chain was exhausted on a CLASSIFIED
        # availability failure (vendor credit/quota/429/5xx/could-not-start), surfaced by
        # fuze-code-action's `availability` output, which is derived from classify.sh's exit
        # code — NEVER from grepping logs, and NEVER from `conclusion` alone (a task failure
        # and an availability exhaustion BOTH report conclusion=failure). This is a
        # NON-BLOCKING notice, check=PASS, and it is deliberately kept DISTINCT from a genuine
        # abstain: nothing in the PR is wrong, so the auto-fix loop must NOT be triggered
        # (an outage passes the check, so fuze-ci-autofix never fires on it — see that
        # workflow). It is the ONE way a non-success conclusion leaves the gate green other
        # than the self-mod deferral above.
        if availability:
            return _result(
                "outage", "pass",
                "fuze-code-action reported an AVAILABILITY failure (vendor credit/quota "
                "exhausted, rate-limited, or the provider could not be reached) — its "
                "`availability` output was true. Per the owner's explicit exception the "
                "required review check does NOT fail on a credit outage: it is not a defect "
                "in this PR. This is a non-blocking notice; re-run once a provider recovers. "
                "The auto-fix loop is deliberately NOT triggered (there is nothing to fix).",
                outage=True,
            )
        # Genuine abstain: a non-success conclusion that is NEITHER the self-mod deferral NOR
        # an availability outage (e.g. a real task failure the reviewer LLM hit). FAIL,
        # fail-closed — a review that could not be produced must never read as a clean one,
        # and it must NOT trigger a code auto-fix (there is nothing to fix), only block + a
        # human comment.
        return _result(
            "abstain", "fail",
            f"fuze-code-action conclusion was {action_conclusion!r}, not 'success', and it "
            "was NOT classified as an availability outage (availability output was false) "
            "nor a self-modification deferral — so no usable review was produced and none "
            "can be approved. Failing closed. See the per-rung 'fuze-code-action' notices in "
            "the job log for the specific classification.",
        )

    parsed, reason = extract_verdict_json(result_text, nonce)
    if parsed is None:
        return _result(
            "abstain", "fail",
            f"reviewer output was unusable: {reason}",
        )

    verdict = parsed["verdict"]
    findings = parsed["findings"]
    summary = parsed["summary"]

    # RULE 5 — SENSITIVE-PATH DOWNGRADE. The MODEL approved, but the PR touches the approval
    # machinery / governance surface, so NO auto-approve is submitted — a human still merges
    # (branch protection's human-approval requirement is unchanged). The CHECK nonetheless
    # PASSES: it keys on the MODEL verdict being `approve`, NOT on whether the GitHub review
    # was an approve vs a comment. Keying the check FAILURE on this downgraded decision would
    # deadlock EVERY governance PR (they all touch the sensitive surface), which is exactly
    # why check=pass here.
    if verdict == "approve" and sensitive_files:
        return _result(
            "comment", "pass",
            "the model's verdict was 'approve', but this PR touches CI/governance "
            "files (" + ", ".join(sensitive_files) + "). A self-approving change to "
            "the approval machinery deserves a human — auto-approve is disabled for "
            "this class of change regardless of review outcome. The check still PASSES: "
            "the MODEL approved, and a human merges.",
            verdict=verdict, summary=summary, findings=findings, downgraded=True,
        )

    if verdict == "approve":
        # Clean model approve on a non-sensitive PR: submit the approving review, PASS.
        return _result(
            "approve", "pass", "ok",
            verdict=verdict, summary=summary, findings=findings,
        )

    if verdict == "request_changes":
        # Blocking issues found. FAIL → triggers the bounded auto-fix loop.
        return _result(
            "request_changes", "fail", "ok",
            verdict=verdict, summary=summary, findings=findings,
        )

    # verdict == "comment": the model was NOT confident enough to approve (with or without
    # findings). On a non-sensitive PR that is not an approval, so the required check FAILS
    # and the auto-fix loop is triggered — the owner's rule is APPROVED or the check fails.
    # (The downgraded and deferred PASS paths above already handled the sensitive cases.)
    return _result(
        "comment", "fail", "ok",
        verdict=verdict, summary=summary, findings=findings,
    )


def render_body(result: dict, mode: str, vendor: str) -> str:
    """Human-readable GitHub review body for the decision `result` from decide()."""
    if result["decision"] == "superseded":
        # Deliberately EMPTY, and asserted empty by the tests. A cancelled run has nothing
        # to say: the newer run on the newer SHA is the one that reviews that commit. The
        # workflow's `superseded)` case posts nothing, so this body is never sent — but it
        # is returned empty rather than left to fall through to the generic renderer, so a
        # future caller that does post it cannot resurrect the noise this rule removes.
        return ""

    lines = ["## fuze-code-review — automated verdict", ""]

    if result["decision"] == "abstain":
        lines.append("**No verdict was reached — this run is NOT an approval.**")
        lines.append("")
        lines.append(result["reason"])
        lines.append("")
        lines.append(
            "This is reported as a failed check deliberately: a review that could not "
            "run must never be silently indistinguishable from a clean one. This is NOT a "
            "code auto-fix trigger — there is nothing in the PR to fix; a human is needed."
        )
        return "\n".join(lines)

    if result["decision"] == "skip":
        lines.append("**Not reviewed this run — this is not a failure.**")
        lines.append("")
        lines.append(result["reason"])
        return "\n".join(lines)

    if result.get("outage"):
        lines.append("**Review skipped on a credit/availability outage — this is not a failure.**")
        lines.append("")
        lines.append(result["reason"])
        lines.append("")
        lines.append(
            "_The required check PASSES per the owner's explicit credit-outage exception. "
            "The required gates and human review still gate this PR. Re-run this workflow "
            "once a provider recovers to get a real review verdict._"
        )
        return "\n".join(lines)

    if result.get("deferred"):
        lines.append("**Review deferred — this is not a failure.**")
        lines.append("")
        lines.append(result["reason"])
        lines.append("")
        lines.append(
            "_Only the automated AI review is deferred; the required gates and human "
            "review still gate this PR. The review runs on the post-merge commit on the "
            "default branch, which no longer modifies the reviewer's own workflow._"
        )
        return "\n".join(lines)

    if result["downgraded"]:
        lines.append("**Human review required — auto-approve disabled for this PR.**")
        lines.append("")
        lines.append(result["reason"])
        lines.append("")

    summary = result.get("summary") or "(no summary provided)"
    lines.append(f"**Summary:** {summary}")
    lines.append("")

    findings = result.get("findings") or []
    if findings:
        lines.append("**Findings:**")
        for f in findings:
            path = f.get("path") or "(unspecified path)"
            line_no = f.get("line")
            loc = f"{path}:{line_no}" if line_no not in (None, "") else path
            lines.append(f"- `{loc}` — {f.get('description', '')}")
        lines.append("")

    decision_label = {
        "approve": "APPROVED — no blocking findings.",
        "request_changes": "CHANGES REQUESTED — see findings above.",
        "comment": "COMMENT ONLY — not an approval.",
    }[result["decision"]]
    lines.append(f"**Verdict:** {decision_label}")
    lines.append("")
    lines.append(f"_Served by fuze-code-action (mode={mode or 'unknown'}, vendor={vendor or 'unknown'})._")
    return "\n".join(lines)


def _write_github_output(decision: dict, body: str) -> None:
    out_path = os.environ.get("GITHUB_OUTPUT")
    if not out_path:
        print(json.dumps({"decision": decision["decision"], "reason": decision["reason"]}))
        return
    delim = f"FUZE_REVIEW_BODY_{_secrets_mod.token_hex(8)}"
    with open(out_path, "a", encoding="utf-8") as fh:
        fh.write(f"decision={decision['decision']}\n")
        # `check` is the authoritative PASS/FAIL the workflow's decisive step exits on.
        fh.write(f"check={decision['check']}\n")
        fh.write(f"body<<{delim}\n{body}\n{delim}\n")


def main() -> int:
    action_conclusion = os.environ.get("FUZE_ACTION_CONCLUSION", "")
    result_text = os.environ.get("FUZE_RESULT_TEXT", "")
    result_text_b64 = os.environ.get("FUZE_RESULT_TEXT_B64", "")
    if not result_text and result_text_b64:
        # GitHub suppresses job outputs that its secret masker considers secret-bearing.
        # CODEX_AUTH_JSON is structured JSON, so review verdict JSON can collide with that
        # heuristic even though it contains no credential. The review job therefore sends
        # the non-secret result as base64 across the job boundary; malformed transport must
        # stay empty so the existing fail-closed verdict path abstains.
        try:
            result_text = base64.b64decode(result_text_b64, validate=True).decode("utf-8")
        except (binascii.Error, UnicodeDecodeError):
            result_text = ""
    nonce = os.environ.get("FUZE_VERDICT_NONCE", "")
    mode = os.environ.get("FUZE_ACTION_MODE", "")
    vendor = os.environ.get("FUZE_ACTION_VENDOR", "")
    # `availability` is fuze-code-action's boolean output derived from classify.sh's exit
    # code (1 = availability). It is the ONLY reliable way to tell a credit/quota outage
    # from a genuine task failure — both report conclusion=failure — so decide() reads it,
    # never the logs. Absent/empty defaults to False (fail-closed: an unknown failure is
    # treated as a real one, not an outage).
    availability = os.environ.get("FUZE_ACTION_AVAILABILITY", "").strip().lower() == "true"
    # `ready` is the review job's own signal (this workflow runs the review in a separate,
    # non-required job so the decisive job's body stays free of the continue-on-error / `||
    # true` machinery a required check may not carry — see the workflow). "true" = a review
    # was attempted; "false" = an environmental skip (no credential / no reviewable diff);
    # anything else (empty) = the review job did not complete and fails closed.
    ready = os.environ.get("FUZE_REVIEW_READY", "true")
    # The review JOB's own result, as GitHub reports it (`needs.review.result`): one of
    # success / failure / cancelled / skipped. Only "cancelled" is consulted — see below.
    # Absent/empty means the workflow does not pass it yet, and every branch behaves
    # exactly as it did before, so an un-updated caller loses nothing.
    job_result = os.environ.get("FUZE_REVIEW_JOB_RESULT", "")
    sensitive_raw = os.environ.get("FUZE_SENSITIVE_FILES", "")
    sensitive_files = [line for line in sensitive_raw.splitlines() if line.strip()]

    if job_result == "cancelled":
        # A CANCELLED REVIEW JOB IS A SUPERSEDE, NOT A VERDICT.
        # This workflow's `concurrency` group cancels the in-flight run whenever a new
        # commit lands, so every push during a review produces one cancelled run. Without
        # this branch such a run falls to the `ready != "true"` abstain below (cancellation
        # kills the job before it can set `ready`) and posts "No verdict was reached — this
        # run is NOT an approval … reported as a failed check deliberately" — wording
        # indistinguishable from a real provider outage, on a run whose only sin was being
        # overtaken by its own author's next push. Measured on FuzeInfra: five such comments
        # across #1188 and #1207, plus four red checks on FuzeSDLC#441. That is not a
        # cosmetic nit. The entire point of the abstain text is to make a review that COULD
        # NOT RUN impossible to mistake for a clean one, and a channel that cries wolf on
        # every push trains readers to skim past the real thing.
        #
        # Keyed on the JOB's result, which GitHub sets, and NEVER on an empty
        # `action_conclusion`: a skipped or never-started review job also yields an empty
        # conclusion and must keep failing closed as an abstain. Only "cancelled" supersedes.
        #
        # Safe to PASS the check: a cancelled run is always superseded by a newer run on a
        # newer SHA, and GitHub evaluates required checks against the HEAD sha — so this
        # verdict can never be the one a merge relies on. It posts NOTHING (see the
        # workflow's `superseded)` case and render_body below).
        result = _result(
            "superseded", "pass",
            "the review job was cancelled, which on this workflow means a newer commit "
            "superseded it. A newer run is reviewing that commit; this one has nothing to "
            "say and posts nothing.",
        )
    elif ready == "false":
        result = _result(
            "skip", "pass",
            "fuze-code-review did not run this time: no LLM credential is configured, or "
            "the PR has no reviewable diff (only excluded lockfiles changed). This is "
            "environmental, not a defect in the PR, so the required check PASSES.",
        )
    elif ready != "true":
        # Empty / unexpected — the review job crashed or was skipped before setting `ready`.
        # A missing review on a REQUIRED gate must fail closed, never pass silently.
        result = _result(
            "abstain", "fail",
            "the review job did not complete (its `ready` signal was "
            f"{ready!r}, neither 'true' nor 'false'). A required review gate must fail "
            "closed when no review was produced rather than pass on a missing signal.",
        )
    else:
        result = decide(action_conclusion, result_text, nonce, sensitive_files, mode, availability)

    body = render_body(result, mode, vendor)

    print(
        f"::notice title=fuze-code-review::decision={result['decision']} "
        f"check={result['check']} reason={result['reason']}"
    )
    _write_github_output(result, body)

    return 0


if __name__ == "__main__":
    sys.exit(main())
