---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fuzekeys-tokenizer-secrets
  namespace: fuzekeys
spec:
  encryptedData:
    LITELLM_MASTER_KEY: AgB7e3AX2kIw2vYNmr4FF4gbE2ZX1WGcLhBytPWqFk6kBPOXL6f/nLcwUtjx1hvG2Guw8b9qXc38Il95bRlEN+V8SxgdIxU/FIf9trJi0xXmnEtWFbwGebrna0HLnN2wF1qFTBAePJTO/MO0fuOe/Ow0OyqRRBGa/+3iwWhSmiDt+bjIPeDJnMcQ3lLiAMuJ/6KZx0bVz17TyFqPvEuIZiXifyU9oiJpVDtM6YwPSQNg3HvKMSFRZXOPY+SVdbtiNnSyIUQrsumxFxRPokT6Qc/ryfzPCTESPVxAfTJ/+tLhtKbzQX0Vwd8sOBBMPIwW8YWwyn4LwlChbk7X9NjKNGibqzGcGIVG1Yu5yVJ3raTBoeMdAOdBNjsaOtE+zsGOkT6zxXbLVjzC49EpWlj5hLrHTNL1VXJHKys6X9Px0QtsjbiU+leZz5iLq4IvyskjaC+cbBCs8yaSpxIAi+V93zmIhgSDwSmecdZ4EkVqx7Ml6o0LiMGlnxBvc2ka84blKA7Zo/IHc7p3OcR9lxF4SGK6IjUv0e74pV+mlzd0HRUPR6ESgZVRi+5bcmBZpnqYE5v+OcGd/IqjMgwRTg+VF1KWCAAcyrjKRuG5ak/pIXF0eAjHBnczdknJdbQr8iBlvOkIXwUjnaGfeF2krbPZNzLN8lWsjul3EpvwtiJqGtz9eYYAFQzzj09wSP2bmSKoaYWDPal5jQWDwoc686FKKugeUkFz2tfpm3dWh/pjd10H4zQ70xZ3eQIVQ+WEwFKzEmVNnIg=
  template:
    metadata:
      creationTimestamp: null
      name: fuzekeys-tokenizer-secrets
      namespace: fuzekeys
