---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: fuzekeys
spec:
  encryptedData:
    .dockerconfigjson: AgBJ8sZvkubEzu/92BgQlm+tzDEApKBY0amLWrWMVk5VAD70BJO/ltUUFQUDNElxvvngutBmB3hUIxP/4CAUSpdtuT+gj0qsFMwLCvwnIRs9/uluqdjmql51cYPkCPENSCmgSsmuwhfNZ9fPwkyQhuVgdpgnInhUm4OihnIWLndmpa/o+BtXtboUEjHwQl33T0t8L7fNhzPQ3pRgc86YOq65GBFTBNkXWiwuWKqEALCvUWjFU9Yxw65ymO77iUcHB/7bSr31KuvYHro2b5WM7FFjo+mZuwtNGez68ImhSHaIeUTON4M5spOcYE9ZTlXoeNKlnulXlKcjlAp1aeqNeXLbEFVZWx91rdqDWQlNhD2HYhW8dcc6RGJiEWN1DnX6G5JpxdYUQCvsW8ecWw7VrtQ9t3EmHUFwXW8AFMyvwOgecDi4ouhu/5CKhBVBQCdr0TvyDSpIE0u8qw/ewy0Yf80GilzpIVSTD9f++fW2JRUWpLEOaOVDQk72HaKOuoD/lkj2eFZeG55+uyPSi/bjLKGUX2DVEFrxCpJw9/LSHNzZ/GZZTIpTY5vu9dJq3g3fZ1t/zclAGPXMJ7RrTKGbVE0bnwVJR+e0IshobZmwNvK2eGMFNJ8zZYI6nK6b3qBQFFHGyz3qA+rtYrFkLDRiTnn7TuNiUG4nK735TdYIX+nXvxURhpfoguFisBcifiYQS8zwC5TeUgkoq0/DjvDwA1oWunCkwphLO0u/BWLgThckSLmp62yP+ocedEvdwLsCbP3rzLQuTBz9aTRTyC5NkbWs0d6xnMwUdrqTinZhKVS4/aJ3E64rxSiOt/QJ6IwW8Q3km8rQFsMmHGlf90MfAXJanL7ltfReFqdX40+jIfFPRORKfCHK1ij6gm7kFSA5YazGPMlaSWb45dTloJm0/PXX+ihwul3LWy/DB5Fouvs/7DbUH/e4C78m1+eOFT51JDph4Cm/Xr+b2fzTgrDNwTKmZdyF
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: fuzekeys
    type: kubernetes.io/dockerconfigjson
