apiVersion: v1
kind: ConfigMap
metadata:
  name: fuzekeys
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    security.fuze.dev/workload-identity: "true"
data:
  service: service:fuzekeys
  serviceAccountName: {{ include "fuzekeys.serviceAccountName" . }}
  scopes: vault:credentials:lease vault:credentials:update
  tokenTtlSeconds: "600"
